"""Closed vocabularies shared by domain models and adapters."""

from enum import StrEnum


class AssetType(StrEnum):
    ETF = "ETF"
    ETF_LINK = "ETF_LINK"
    INDEX_FUND = "INDEX_FUND"
    UNKNOWN = "UNKNOWN"


class FeeDataStatus(StrEnum):
    UNKNOWN = "UNKNOWN"
    USER_PROVIDED = "USER_PROVIDED"
    OFFICIAL_VERIFIED = "OFFICIAL_VERIFIED"


class PositionRiskBand(StrEnum):
    WITHIN_PLAN = "WITHIN_PLAN"
    LOSS_WARNING = "LOSS_WARNING"
    REANALYSIS_REQUIRED = "REANALYSIS_REQUIRED"


class EntityType(StrEnum):
    COMPANY = "COMPANY"
    COMMODITY = "COMMODITY"
    INDEX = "INDEX"
    PRODUCT = "PRODUCT"
    TECHNOLOGY = "TECHNOLOGY"
    REGION = "REGION"


class TopicCategory(StrEnum):
    THEME = "THEME"
    SUBTHEME = "SUBTHEME"
    END_MARKET = "END_MARKET"


class TaxonomyNodeKind(StrEnum):
    TOPIC = "TOPIC"
    ENTITY = "ENTITY"


class InfluenceDirection(StrEnum):
    POSITIVE = "POSITIVE"
    NEGATIVE = "NEGATIVE"
    MIXED = "MIXED"
    CONTEXT_DEPENDENT = "CONTEXT_DEPENDENT"


class ExposureDataStatus(StrEnum):
    UNKNOWN = "UNKNOWN"
    HEURISTIC = "HEURISTIC"
    OFFICIAL_VERIFIED = "OFFICIAL_VERIFIED"


class ExposureKind(StrEnum):
    DIRECT = "DIRECT"
    UPSTREAM = "UPSTREAM"
    DOWNSTREAM = "DOWNSTREAM"
    INPUT_COST = "INPUT_COST"
    DEMAND_DRIVER = "DEMAND_DRIVER"


class SourceKind(StrEnum):
    REGULATOR = "REGULATOR"
    FUND_MANAGER = "FUND_MANAGER"
    COMPANY_OFFICIAL = "COMPANY_OFFICIAL"
    RESEARCH = "RESEARCH"
    NEWS = "NEWS"
    MARKET_DATA = "MARKET_DATA"
    COMMUNITY = "COMMUNITY"


class FetchErrorCode(StrEnum):
    INVALID_URL = "INVALID_URL"
    SCHEME_REJECTED = "SCHEME_REJECTED"
    HOST_REJECTED = "HOST_REJECTED"
    PORT_REJECTED = "PORT_REJECTED"
    DNS_FAILED = "DNS_FAILED"
    ADDRESS_REJECTED = "ADDRESS_REJECTED"
    REDIRECT_REJECTED = "REDIRECT_REJECTED"
    REDIRECT_LIMIT = "REDIRECT_LIMIT"
    TIMEOUT = "TIMEOUT"
    HTTP_STATUS = "HTTP_STATUS"
    CONTENT_TYPE_REJECTED = "CONTENT_TYPE_REJECTED"
    RESPONSE_TOO_LARGE = "RESPONSE_TOO_LARGE"
    NETWORK_ERROR = "NETWORK_ERROR"
    CIRCUIT_OPEN = "CIRCUIT_OPEN"


class SourceHealthStatus(StrEnum):
    HEALTHY = "HEALTHY"
    DEGRADED = "DEGRADED"
    CIRCUIT_OPEN = "CIRCUIT_OPEN"


class TrustTier(StrEnum):
    PRIMARY = "PRIMARY"
    PROFESSIONAL = "PROFESSIONAL"
    SECONDARY = "SECONDARY"
    SENTIMENT_ONLY = "SENTIMENT_ONLY"


class DocumentState(StrEnum):
    DISCOVERED = "DISCOVERED"
    FETCHED = "FETCHED"
    NORMALIZED = "NORMALIZED"
    DEDUPLICATED = "DEDUPLICATED"
    CLASSIFIED = "CLASSIFIED"
    EXTRACTED = "EXTRACTED"
    SCORED = "SCORED"
    ANALYZED = "ANALYZED"
    PUBLISHED = "PUBLISHED"
    RETRYABLE_FAILED = "RETRYABLE_FAILED"
    PERMANENT_FAILED = "PERMANENT_FAILED"
    QUARANTINED = "QUARANTINED"


class EvidenceDirection(StrEnum):
    POSITIVE = "POSITIVE"
    NEGATIVE = "NEGATIVE"
    NEUTRAL = "NEUTRAL"
    MIXED = "MIXED"
    UNKNOWN = "UNKNOWN"


class SuggestionLabel(StrEnum):
    INSUFFICIENT_DATA = "INSUFFICIENT_DATA"
    OBSERVE = "OBSERVE"
    HOLD = "HOLD"
    SMALL_ADD = "SMALL_ADD"
    PAUSE_ADDING = "PAUSE_ADDING"
    REBALANCE = "REBALANCE"
    REDUCE = "REDUCE"


class JobStatus(StrEnum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    SUCCEEDED = "SUCCEEDED"
    RETRYABLE_FAILED = "RETRYABLE_FAILED"
    PERMANENT_FAILED = "PERMANENT_FAILED"
    CANCELLED = "CANCELLED"


class TransitionOutcome(StrEnum):
    APPLIED = "APPLIED"
    NOOP = "NOOP"
    REJECTED = "REJECTED"


class ReportFormat(StrEnum):
    MARKDOWN = "MARKDOWN"
    HTML = "HTML"
    PDF = "PDF"
