"""initial storage schema

Revision ID: 0001
Revises:
Create Date: 2026-07-19 22:07:45.461738
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "workspaces",
        sa.Column("workspace_id", sa.String(length=128), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("workspace_id", name=op.f("pk_workspaces")),
    )
    op.create_table(
        "assets",
        sa.Column("asset_id", sa.String(length=128), nullable=False),
        sa.Column("fund_code", sa.String(length=32), nullable=False),
        sa.Column("asset_type", sa.String(length=32), nullable=False),
        sa.Column("schema_version", sa.String(length=32), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("workspace_id", sa.String(length=128), nullable=False),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.workspace_id"],
            name=op.f("fk_assets_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("asset_id", name=op.f("pk_assets")),
        sa.UniqueConstraint("workspace_id", "asset_id", name="uq_assets_workspace_asset"),
        sa.UniqueConstraint("workspace_id", "fund_code", name="uq_assets_workspace_fund_code"),
    )
    with op.batch_alter_table("assets", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_assets_workspace_id"), ["workspace_id"], unique=False)

    op.create_table(
        "audit_events",
        sa.Column("audit_event_id", sa.String(length=128), nullable=False),
        sa.Column("event_type", sa.String(length=128), nullable=False),
        sa.Column("actor", sa.String(length=128), nullable=False),
        sa.Column("target_type", sa.String(length=128), nullable=False),
        sa.Column("target_id", sa.String(length=128), nullable=False),
        sa.Column("outcome", sa.String(length=32), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.Column("workspace_id", sa.String(length=128), nullable=False),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.workspace_id"],
            name=op.f("fk_audit_events_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("audit_event_id", name=op.f("pk_audit_events")),
    )
    with op.batch_alter_table("audit_events", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_audit_events_workspace_id"), ["workspace_id"], unique=False
        )
        batch_op.create_index(
            "ix_audit_events_workspace_occurred", ["workspace_id", "occurred_at"], unique=False
        )

    op.create_table(
        "entities",
        sa.Column("entity_id", sa.String(length=128), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("entity_type", sa.String(length=32), nullable=False),
        sa.Column("schema_version", sa.String(length=32), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("workspace_id", sa.String(length=128), nullable=False),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.workspace_id"],
            name=op.f("fk_entities_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("entity_id", name=op.f("pk_entities")),
        sa.UniqueConstraint("workspace_id", "entity_id", name="uq_entities_workspace_entity"),
        sa.UniqueConstraint(
            "workspace_id", "name", "entity_type", name="uq_entities_workspace_name_type"
        ),
    )
    with op.batch_alter_table("entities", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_entities_workspace_id"), ["workspace_id"], unique=False
        )

    op.create_table(
        "idempotency_records",
        sa.Column("idempotency_record_id", sa.String(length=128), nullable=False),
        sa.Column("scope", sa.String(length=128), nullable=False),
        sa.Column("key", sa.String(length=128), nullable=False),
        sa.Column("payload_sha256", sa.String(length=64), nullable=False),
        sa.Column("record_type", sa.String(length=128), nullable=False),
        sa.Column("record_id", sa.String(length=128), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("workspace_id", sa.String(length=128), nullable=False),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.workspace_id"],
            name=op.f("fk_idempotency_records_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("idempotency_record_id", name=op.f("pk_idempotency_records")),
        sa.UniqueConstraint(
            "workspace_id", "scope", "key", name="uq_idempotency_workspace_scope_key"
        ),
    )
    with op.batch_alter_table("idempotency_records", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_idempotency_records_workspace_id"), ["workspace_id"], unique=False
        )

    op.create_table(
        "investment_profiles",
        sa.Column("profile_id", sa.String(length=128), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("schema_version", sa.String(length=32), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("workspace_id", sa.String(length=128), nullable=False),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.workspace_id"],
            name=op.f("fk_investment_profiles_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("profile_id", name=op.f("pk_investment_profiles")),
        sa.UniqueConstraint(
            "workspace_id", "profile_id", name="uq_investment_profiles_workspace_profile"
        ),
    )
    with op.batch_alter_table("investment_profiles", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_investment_profiles_workspace_id"), ["workspace_id"], unique=False
        )

    op.create_table(
        "sources",
        sa.Column("source_id", sa.String(length=128), nullable=False),
        sa.Column("base_url", sa.String(length=2048), nullable=False),
        sa.Column("adapter_name", sa.String(length=128), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("schema_version", sa.String(length=32), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("workspace_id", sa.String(length=128), nullable=False),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.workspace_id"],
            name=op.f("fk_sources_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("source_id", name=op.f("pk_sources")),
        sa.UniqueConstraint("workspace_id", "base_url", name="uq_sources_workspace_base_url"),
        sa.UniqueConstraint("workspace_id", "source_id", name="uq_sources_workspace_source"),
    )
    with op.batch_alter_table("sources", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_sources_workspace_id"), ["workspace_id"], unique=False)

    op.create_table(
        "topics",
        sa.Column("topic_id", sa.String(length=128), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("config_version", sa.String(length=64), nullable=False),
        sa.Column("schema_version", sa.String(length=32), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("workspace_id", sa.String(length=128), nullable=False),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.workspace_id"],
            name=op.f("fk_topics_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("topic_id", name=op.f("pk_topics")),
        sa.UniqueConstraint(
            "workspace_id", "name", "config_version", name="uq_topics_workspace_name_version"
        ),
        sa.UniqueConstraint("workspace_id", "topic_id", name="uq_topics_workspace_topic"),
    )
    with op.batch_alter_table("topics", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_topics_workspace_id"), ["workspace_id"], unique=False)

    op.create_table(
        "analysis_runs",
        sa.Column("analysis_run_id", sa.String(length=128), nullable=False),
        sa.Column("asset_id", sa.String(length=128), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("pipeline_version", sa.String(length=120), nullable=False),
        sa.Column("prompt_version", sa.String(length=120), nullable=False),
        sa.Column("input_snapshot", sa.JSON(), nullable=False),
        sa.Column("schema_version", sa.String(length=32), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("workspace_id", sa.String(length=128), nullable=False),
        sa.ForeignKeyConstraint(
            ["workspace_id", "asset_id"],
            ["assets.workspace_id", "assets.asset_id"],
            name="fk_analysis_runs_workspace_asset",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.workspace_id"],
            name=op.f("fk_analysis_runs_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("analysis_run_id", name=op.f("pk_analysis_runs")),
        sa.UniqueConstraint(
            "workspace_id", "analysis_run_id", name="uq_analysis_runs_workspace_run"
        ),
        sa.UniqueConstraint(
            "workspace_id", "idempotency_key", name="uq_analysis_runs_workspace_idempotency"
        ),
    )
    with op.batch_alter_table("analysis_runs", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_analysis_runs_workspace_id"), ["workspace_id"], unique=False
        )

    op.create_table(
        "crawl_runs",
        sa.Column("crawl_run_id", sa.String(length=128), nullable=False),
        sa.Column("source_id", sa.String(length=128), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("scheduled_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("schema_version", sa.String(length=32), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("workspace_id", sa.String(length=128), nullable=False),
        sa.ForeignKeyConstraint(
            ["workspace_id", "source_id"],
            ["sources.workspace_id", "sources.source_id"],
            name="fk_crawl_runs_workspace_source",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.workspace_id"],
            name=op.f("fk_crawl_runs_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("crawl_run_id", name=op.f("pk_crawl_runs")),
        sa.UniqueConstraint(
            "workspace_id", "idempotency_key", name="uq_crawl_runs_workspace_idempotency"
        ),
    )
    with op.batch_alter_table("crawl_runs", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_crawl_runs_workspace_id"), ["workspace_id"], unique=False
        )

    op.create_table(
        "exposures",
        sa.Column("exposure_id", sa.String(length=128), nullable=False),
        sa.Column("asset_id", sa.String(length=128), nullable=False),
        sa.Column("topic_id", sa.String(length=128), nullable=False),
        sa.Column("entity_id", sa.String(length=128), nullable=True),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("config_version", sa.String(length=64), nullable=False),
        sa.Column("schema_version", sa.String(length=32), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("workspace_id", sa.String(length=128), nullable=False),
        sa.ForeignKeyConstraint(
            ["workspace_id", "asset_id"],
            ["assets.workspace_id", "assets.asset_id"],
            name="fk_exposures_workspace_asset",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "entity_id"],
            ["entities.workspace_id", "entities.entity_id"],
            name="fk_exposures_workspace_entity",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "topic_id"],
            ["topics.workspace_id", "topics.topic_id"],
            name="fk_exposures_workspace_topic",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.workspace_id"],
            name=op.f("fk_exposures_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("exposure_id", name=op.f("pk_exposures")),
        sa.UniqueConstraint(
            "workspace_id",
            "asset_id",
            "topic_id",
            "entity_id",
            "kind",
            "config_version",
            name="uq_exposures_workspace_mapping_version",
        ),
    )
    with op.batch_alter_table("exposures", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_exposures_workspace_id"), ["workspace_id"], unique=False
        )

    op.create_table(
        "positions",
        sa.Column("position_id", sa.String(length=128), nullable=False),
        sa.Column("profile_id", sa.String(length=128), nullable=False),
        sa.Column("asset_id", sa.String(length=128), nullable=False),
        sa.Column("snapshot_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("schema_version", sa.String(length=32), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("workspace_id", sa.String(length=128), nullable=False),
        sa.ForeignKeyConstraint(
            ["workspace_id", "asset_id"],
            ["assets.workspace_id", "assets.asset_id"],
            name="fk_positions_workspace_asset",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "profile_id"],
            ["investment_profiles.workspace_id", "investment_profiles.profile_id"],
            name="fk_positions_workspace_profile",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.workspace_id"],
            name=op.f("fk_positions_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("position_id", name=op.f("pk_positions")),
        sa.UniqueConstraint(
            "workspace_id", "asset_id", "snapshot_at", name="uq_positions_workspace_asset_snapshot"
        ),
    )
    with op.batch_alter_table("positions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_positions_workspace_id"), ["workspace_id"], unique=False
        )

    op.create_table(
        "raw_documents",
        sa.Column("document_id", sa.String(length=128), nullable=False),
        sa.Column("source_id", sa.String(length=128), nullable=False),
        sa.Column("source_url", sa.String(length=2048), nullable=False),
        sa.Column("title", sa.String(length=1000), nullable=False),
        sa.Column("raw_body", sa.Text(), nullable=True),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("schema_version", sa.String(length=32), nullable=False),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column("state_version", sa.Integer(), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("body_purged_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("metadata_payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("workspace_id", sa.String(length=128), nullable=False),
        sa.CheckConstraint(
            "state_version >= 0", name=op.f("ck_raw_documents_state_version_nonnegative")
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "source_id"],
            ["sources.workspace_id", "sources.source_id"],
            name="fk_raw_documents_workspace_source",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.workspace_id"],
            name=op.f("fk_raw_documents_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("document_id", name=op.f("pk_raw_documents")),
        sa.UniqueConstraint(
            "workspace_id", "content_hash", name="uq_raw_documents_workspace_content_hash"
        ),
        sa.UniqueConstraint(
            "workspace_id", "document_id", name="uq_raw_documents_workspace_document"
        ),
    )
    with op.batch_alter_table("raw_documents", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_raw_documents_workspace_id"), ["workspace_id"], unique=False
        )
        batch_op.create_index(
            "ix_raw_documents_workspace_state", ["workspace_id", "state"], unique=False
        )

    op.create_table(
        "decision_results",
        sa.Column("decision_id", sa.String(length=128), nullable=False),
        sa.Column("analysis_run_id", sa.String(length=128), nullable=False),
        sa.Column("label", sa.String(length=32), nullable=False),
        sa.Column("rule_version", sa.String(length=120), nullable=False),
        sa.Column("schema_version", sa.String(length=32), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("workspace_id", sa.String(length=128), nullable=False),
        sa.ForeignKeyConstraint(
            ["workspace_id", "analysis_run_id"],
            ["analysis_runs.workspace_id", "analysis_runs.analysis_run_id"],
            name="fk_decision_results_workspace_analysis",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.workspace_id"],
            name=op.f("fk_decision_results_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("decision_id", name=op.f("pk_decision_results")),
    )
    with op.batch_alter_table("decision_results", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_decision_results_workspace_id"), ["workspace_id"], unique=False
        )

    op.create_table(
        "event_clusters",
        sa.Column("cluster_id", sa.String(length=128), nullable=False),
        sa.Column("event_key", sa.String(length=300), nullable=False),
        sa.Column("canonical_document_id", sa.String(length=128), nullable=False),
        sa.Column("schema_version", sa.String(length=32), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("workspace_id", sa.String(length=128), nullable=False),
        sa.ForeignKeyConstraint(
            ["workspace_id", "canonical_document_id"],
            ["raw_documents.workspace_id", "raw_documents.document_id"],
            name="fk_event_clusters_workspace_document",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.workspace_id"],
            name=op.f("fk_event_clusters_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("cluster_id", name=op.f("pk_event_clusters")),
        sa.UniqueConstraint(
            "workspace_id", "cluster_id", name="uq_event_clusters_workspace_cluster"
        ),
        sa.UniqueConstraint(
            "workspace_id", "event_key", name="uq_event_clusters_workspace_event_key"
        ),
    )
    with op.batch_alter_table("event_clusters", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_event_clusters_workspace_id"), ["workspace_id"], unique=False
        )

    op.create_table(
        "reports",
        sa.Column("report_id", sa.String(length=128), nullable=False),
        sa.Column("analysis_run_id", sa.String(length=128), nullable=False),
        sa.Column("pipeline_version", sa.String(length=120), nullable=False),
        sa.Column("rule_version", sa.String(length=120), nullable=False),
        sa.Column("prompt_version", sa.String(length=120), nullable=False),
        sa.Column("input_snapshot", sa.JSON(), nullable=False),
        sa.Column("schema_version", sa.String(length=32), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("workspace_id", sa.String(length=128), nullable=False),
        sa.ForeignKeyConstraint(
            ["workspace_id", "analysis_run_id"],
            ["analysis_runs.workspace_id", "analysis_runs.analysis_run_id"],
            name="fk_reports_workspace_analysis",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.workspace_id"],
            name=op.f("fk_reports_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("report_id", name=op.f("pk_reports")),
    )
    with op.batch_alter_table("reports", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_reports_workspace_id"), ["workspace_id"], unique=False)

    op.create_table(
        "evidence_items",
        sa.Column("evidence_id", sa.String(length=128), nullable=False),
        sa.Column("document_id", sa.String(length=128), nullable=False),
        sa.Column("cluster_id", sa.String(length=128), nullable=True),
        sa.Column("schema_version", sa.String(length=32), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("workspace_id", sa.String(length=128), nullable=False),
        sa.ForeignKeyConstraint(
            ["workspace_id", "cluster_id"],
            ["event_clusters.workspace_id", "event_clusters.cluster_id"],
            name="fk_evidence_items_workspace_cluster",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "document_id"],
            ["raw_documents.workspace_id", "raw_documents.document_id"],
            name="fk_evidence_items_workspace_document",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.workspace_id"],
            name=op.f("fk_evidence_items_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("evidence_id", name=op.f("pk_evidence_items")),
        sa.UniqueConstraint(
            "workspace_id", "evidence_id", name="uq_evidence_items_workspace_evidence"
        ),
    )
    with op.batch_alter_table("evidence_items", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_evidence_items_workspace_id"), ["workspace_id"], unique=False
        )

    op.create_table(
        "evidence_scores",
        sa.Column("score_id", sa.String(length=128), nullable=False),
        sa.Column("evidence_id", sa.String(length=128), nullable=False),
        sa.Column("scoring_version", sa.String(length=120), nullable=False),
        sa.Column("schema_version", sa.String(length=32), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("workspace_id", sa.String(length=128), nullable=False),
        sa.ForeignKeyConstraint(
            ["workspace_id", "evidence_id"],
            ["evidence_items.workspace_id", "evidence_items.evidence_id"],
            name="fk_evidence_scores_workspace_evidence",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.workspace_id"],
            name=op.f("fk_evidence_scores_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("score_id", name=op.f("pk_evidence_scores")),
        sa.UniqueConstraint(
            "workspace_id",
            "evidence_id",
            "scoring_version",
            name="uq_evidence_scores_workspace_evidence_version",
        ),
    )
    with op.batch_alter_table("evidence_scores", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_evidence_scores_workspace_id"), ["workspace_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("evidence_scores", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_evidence_scores_workspace_id"))

    op.drop_table("evidence_scores")
    with op.batch_alter_table("evidence_items", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_evidence_items_workspace_id"))

    op.drop_table("evidence_items")
    with op.batch_alter_table("reports", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_reports_workspace_id"))

    op.drop_table("reports")
    with op.batch_alter_table("event_clusters", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_event_clusters_workspace_id"))

    op.drop_table("event_clusters")
    with op.batch_alter_table("decision_results", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_decision_results_workspace_id"))

    op.drop_table("decision_results")
    with op.batch_alter_table("raw_documents", schema=None) as batch_op:
        batch_op.drop_index("ix_raw_documents_workspace_state")
        batch_op.drop_index(batch_op.f("ix_raw_documents_workspace_id"))

    op.drop_table("raw_documents")
    with op.batch_alter_table("positions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_positions_workspace_id"))

    op.drop_table("positions")
    with op.batch_alter_table("exposures", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_exposures_workspace_id"))

    op.drop_table("exposures")
    with op.batch_alter_table("crawl_runs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_crawl_runs_workspace_id"))

    op.drop_table("crawl_runs")
    with op.batch_alter_table("analysis_runs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_analysis_runs_workspace_id"))

    op.drop_table("analysis_runs")
    with op.batch_alter_table("topics", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_topics_workspace_id"))

    op.drop_table("topics")
    with op.batch_alter_table("sources", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sources_workspace_id"))

    op.drop_table("sources")
    with op.batch_alter_table("investment_profiles", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_investment_profiles_workspace_id"))

    op.drop_table("investment_profiles")
    with op.batch_alter_table("idempotency_records", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_idempotency_records_workspace_id"))

    op.drop_table("idempotency_records")
    with op.batch_alter_table("entities", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_entities_workspace_id"))

    op.drop_table("entities")
    with op.batch_alter_table("audit_events", schema=None) as batch_op:
        batch_op.drop_index("ix_audit_events_workspace_occurred")
        batch_op.drop_index(batch_op.f("ix_audit_events_workspace_id"))

    op.drop_table("audit_events")
    with op.batch_alter_table("assets", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_assets_workspace_id"))

    op.drop_table("assets")
    op.drop_table("workspaces")
    # ### end Alembic commands ###
