"""add immutable position snapshots

Revision ID: 0003
Revises: 0002
Create Date: 2026-07-19 23:14:58.704634
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0003"
down_revision: str | Sequence[str] | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "position_snapshots",
        sa.Column("snapshot_id", sa.String(length=128), nullable=False),
        sa.Column("position_id", sa.String(length=128), nullable=False),
        sa.Column("asset_id", sa.String(length=128), nullable=False),
        sa.Column("purpose", sa.String(length=32), nullable=False),
        sa.Column("schema_version", sa.String(length=32), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("generated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("workspace_id", sa.String(length=128), nullable=False),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.workspace_id"],
            name=op.f("fk_position_snapshots_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("snapshot_id", name=op.f("pk_position_snapshots")),
        sa.UniqueConstraint(
            "workspace_id", "snapshot_id", name="uq_position_snapshots_workspace_snapshot"
        ),
    )
    with op.batch_alter_table("position_snapshots", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_position_snapshots_workspace_id"), ["workspace_id"], unique=False
        )
        batch_op.create_index(
            "ix_position_snapshots_workspace_position_generated",
            ["workspace_id", "position_id", "generated_at"],
            unique=False,
        )

    with op.batch_alter_table("analysis_runs", schema=None) as batch_op:
        batch_op.add_column(sa.Column("position_snapshot_id", sa.String(length=128), nullable=True))
        batch_op.create_foreign_key(
            "fk_analysis_runs_workspace_position_snapshot",
            "position_snapshots",
            ["workspace_id", "position_snapshot_id"],
            ["workspace_id", "snapshot_id"],
            ondelete="RESTRICT",
        )

    with op.batch_alter_table("positions", schema=None) as batch_op:
        batch_op.drop_constraint("uq_positions_workspace_asset_snapshot", type_="unique")
        batch_op.create_unique_constraint(
            "uq_positions_workspace_position", ["workspace_id", "position_id"]
        )
        batch_op.create_unique_constraint(
            "uq_positions_workspace_profile_asset_snapshot",
            ["workspace_id", "profile_id", "asset_id", "snapshot_at"],
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("positions", schema=None) as batch_op:
        batch_op.drop_constraint("uq_positions_workspace_profile_asset_snapshot", type_="unique")
        batch_op.drop_constraint("uq_positions_workspace_position", type_="unique")
        batch_op.create_unique_constraint(
            "uq_positions_workspace_asset_snapshot",
            ["workspace_id", "asset_id", "snapshot_at"],
        )

    with op.batch_alter_table("analysis_runs", schema=None) as batch_op:
        batch_op.drop_constraint("fk_analysis_runs_workspace_position_snapshot", type_="foreignkey")
        batch_op.drop_column("position_snapshot_id")

    with op.batch_alter_table("position_snapshots", schema=None) as batch_op:
        batch_op.drop_index("ix_position_snapshots_workspace_position_generated")
        batch_op.drop_index(batch_op.f("ix_position_snapshots_workspace_id"))

    op.drop_table("position_snapshots")
    # ### end Alembic commands ###
